[project]
name = "pixi-hello-world"
version = "0.1.0"
description = "Add a short description here"
authors = ["Davirain <davirain.yin@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
hello = "python hello_world.py"

[dependencies]
python = ">=3.12.3,<3.13"
